import { Plus_Jakarta_Sans, Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { Providers } from "./providers";
import Footer from "@/components/shared/Footer";


const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-jakarta", // Body text variable
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["700", "800", "900"],
  variable: "--font-outfit", // Heading text variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    
      lang="en"
      className={` h-full antialiased`}
      suppressHydrationWarning
    >
      <body className={`${jakartaSans.variable} ${outfit.variable} min-h-full flex flex-col bg-background text-foreground`}>
        <Providers>
          <Navbar/>
        <main> {children}</main>
        <Footer/>
        </Providers>
        
       
        </body>
    </html>
  );
}
